[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./deployments/"}]
remappings = ["@openzeppelin/=node_modules/@openzeppelin"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
